```{r}
set.seed(151)
oldpar <- par(mfrow=c(2,2))

tenfold1000 <- rep(1:10, rep(1000,10))

boxplot(split(rnorm(1000*10), tenfold1000), ylab="normal - 1000")
boxplot(split(rt(1000*10, 7), tenfold1000),
        ylab=expression(t[7]*" - 1000"))

tenfold100 <- rep(1:10, rep(100, 10))

boxplot(split(rnorm(100*10), tenfold100), ylab="normal - 100")
boxplot(split(rt(100*10, 7), tenfold100),
        ylab=expression(t[7]*" - 100")) 

par(oldpar)
```


The analisys over these boxplots follows a top-down structure. So, the first things that we may say are related with the mean. In fact each set of $10$ boxplots have, more or less, the same mean value, i.e. around $0$, but with a very small fluctuation in the $100$ samples cases. The same happens on the maximum and minimum values but with different values in case the samples come from a normal distribution or $t$ distribution, but in this case we have to look according to which distribution the samples belong to (more details will be given later). Last comment on the overall boxplots is about the box-size defined by the quantiles: as we can see the box-size for the normal distributions is larger than the box-size for the $t$ distribution, also if we consider the set of boxplots with less samples.

Now, we may say something more by looking each of the four set of boxes. In the top-left quarter, the max and min values are, more or less, close to $2.3$ in absolute value, and it is the same for the first and third quantiles; this is quite important because it means this normal distribution is very simmetric. 

The boxplot might detect some points like a possible outliers, and this is shown by the set of points outside the "whiskers"; in particular, more far from the first and third quantiles they are and more suitable they are to be outliers. Moreover, from the heavy-tailed definition we know that a general distribution is classified as an heavy-tailed if its boxplot shows some candidate outliers in both sides of the "whiskers", otherwise it is classfied as a skewed distribution (i.e. we detect some outliers in just one of the two sides).

So, in this case we may suspect to deal with a heavy-tailed distribution, and more than half boxes have some plausibles outliers (i.e. they are far enough from the "whiskers").

In the bottom-left quarter, max and min values are not anymore fixed as in the previous situation: now, each boxplot has its how values for them, but in any case they differ by some units. Moreover, the first and third quantiles are no more fixed in each boxes, and the "whiskers" on both sides have different distances, so this event is interesting because it shows the asymmetry of the distribution with not so much samples. In this set of boxplots, we may expect to have one point as possible outlier for each box, and some of them follow this assumption but just less than half set has outliers; in addition, this set seems to be skewed. Quite the opposite than the previous one.

In the top-right quarter we have a $t$ distribution and this case is very similar to the first one, but having different values for min, max and quantiles. Moreover, these parameters remain fixed and the "whiskers" have the same length, so the symmetry is respected. In the end, for what concerns possible outliers and heavy-tailed configuration we have to be careful, because most of the outside points are very close to each other and very close to the "whiskers" borders, so it is not so immediate to say something; a more deep analysis is suggested in this case.

In the bottom-right quarter, things are now similar to the bottom-left quarter, so the simmetry is not anymore present and the boxes have different sizes. However, in this last case, there are more possible outliers along the different boxes, and they are more easily localized (in contrast with the previous case in which it's not true); as well as we may suppose they have a skewed structure.
